"""baseline_clean_models

Revision ID: 9cf4f896dba0
Revises: 
Create Date: 2026-04-30 09:23:43.800689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf4f896dba0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hitter_career_stats', schema=None) as batch_op:
        batch_op.drop_column('rbi')
        batch_op.drop_column('r')

    with op.batch_alter_table('hitter_performance_daily', schema=None) as batch_op:
        batch_op.drop_column('rbi')
        batch_op.drop_column('r')

    with op.batch_alter_table('pitcher_career_stats', schema=None) as batch_op:
        batch_op.drop_column('losses')
        batch_op.drop_column('saves')
        batch_op.drop_column('wins')

    with op.batch_alter_table('pitcher_performance_daily', schema=None) as batch_op:
        batch_op.drop_column('losses')
        batch_op.drop_column('saves')
        batch_op.drop_column('wins')

    with op.batch_alter_table('stc_pitches', schema=None) as batch_op:
        batch_op.drop_column('csw')
        batch_op.drop_column('hardness')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stc_pitches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hardness', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('csw', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('pitcher_performance_daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('saves', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('pitcher_career_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wins', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('saves', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('losses', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('hitter_performance_daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('r', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rbi', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('hitter_career_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('r', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rbi', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
