"""add_new_venue_dimensions

Revision ID: d8c70c0042f2
Revises: 9cf4f896dba0
Create Date: 2026-04-30 10:12:32.125679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8c70c0042f2'
down_revision: Union[str, Sequence[str], None] = '9cf4f896dba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('left', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('left_center', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('right_center', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('right', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_column('right')
        batch_op.drop_column('right_center')
        batch_op.drop_column('left_center')
        batch_op.drop_column('left')

    # ### end Alembic commands ###
